leaf1:
  tags: [ arcos, router ]
  address: 1.1.1.1
  device_type: arcos
  context: 
    - site: sitea
    - role: router
leaf2:
  tags: [ arcos, router ]
  address: 1.1.1.2
  device_type: arcos
  context: 
    - site: sitea
    - role: router
leaf3:
  tags: [ arcos, router ]
  address: 1.1.1.3
  device_type: arcos
  context:
    - site: sitea
    - role: router
